# Generated by Django 4.1.6 on 2023-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("HI", "Hindi"),
                            ("MR", "Marathi"),
                            ("KN", "Kannada"),
                            ("TA", "Tamil"),
                            ("TE", "Telugu"),
                        ],
                        max_length=2,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
            ],
        ),
    ]
