// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbcQT_CQ5S9OqIXLZkRfykQGGSWRbiCE',
    appId: '1:869421884116:web:643d5a9dcbec54eac65141',
    messagingSenderId: '869421884116',
    projectId: 'indian-language-teacher',
    authDomain: 'indian-language-teacher.firebaseapp.com',
    storageBucket: 'indian-language-teacher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLrVYXAyFKTt75Keq5cL4wA-BCUk0VSbU',
    appId: '1:869421884116:android:05b1f53dda8740d7c65141',
    messagingSenderId: '869421884116',
    projectId: 'indian-language-teacher',
    storageBucket: 'indian-language-teacher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNn2VmvuP_WYPL8y-QboFObBuC6dye6nY',
    appId: '1:869421884116:ios:076e9c3c64ef0f26c65141',
    messagingSenderId: '869421884116',
    projectId: 'indian-language-teacher',
    storageBucket: 'indian-language-teacher.appspot.com',
    iosClientId: '869421884116-vp31da3lhknm2l49ds1da836espvlclo.apps.googleusercontent.com',
    iosBundleId: 'com.example.indianLanguageTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNn2VmvuP_WYPL8y-QboFObBuC6dye6nY',
    appId: '1:869421884116:ios:076e9c3c64ef0f26c65141',
    messagingSenderId: '869421884116',
    projectId: 'indian-language-teacher',
    storageBucket: 'indian-language-teacher.appspot.com',
    iosClientId: '869421884116-vp31da3lhknm2l49ds1da836espvlclo.apps.googleusercontent.com',
    iosBundleId: 'com.example.indianLanguageTeacher',
  );
}
